development:
  adapter: postgresql
  encoding: unicode
  database: maujan_development
  pool: 5
  username: kureshy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: maujan_test
  pool: 5
  username: kureshy
  password: